### ISSUE TITLE
IndexError Issue

### ISSUE THREAD

**Issue by LeeTaylor-git** [jdaymude/xbox2local#28]
I'm having an IndexError issue on Windows 11 when running the xbox2local program. Here is the message in CMD:

Scanning the Xbox network for screenshots...
Traceback (most recent call last):
  File "C:\Path\xbox2local.py", line 147, in <module>
    screens, cont_token = make_api_call(api_key, screens_endpoint)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\xbox2local.py", line 41, in make_api_call
    http_status = output[0].split()[1]
                  ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by LeeTaylor-git** [comment]
Any chance someone can help with this?

**Comment by memiks** [comment]
Hi @LeeTaylor-git ,

You need to go to https://xbl.io/profile
connect to it
and verify your account (send a code to a mobile phone and provide it).

Then it should work (activate the API Key)

**Comment by LeeTaylor-git** [comment]
Hello @memiks,

I already have an account on xbl.io and an active API key.

**Comment by memiks** [comment]
Same for me but I needed to revalidate it again after months without issues.

**Comment by LeeTaylor-git** [comment]
@memiks, I don’t see where I can revalidate my account. Can you provide a screenshot?
